# Generated by Django 5.2.3 on 2025-06-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=64)),
                ("icon", models.CharField(max_length=128)),
                ("item_class", models.CharField(db_index=True, max_length=32)),
                ("item_subclass", models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PlayableClass",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=14, unique=True)),
                ("icon", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "Playable Classes",
            },
        ),
        migrations.CreateModel(
            name="PlayableRace",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=24)),
            ],
            options={
                "verbose_name_plural": "Playable Races",
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16)),
                ("icon", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Reagent",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="PlayableSpecialization",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=16)),
                ("icon", models.CharField(max_length=128)),
                ("role", models.CharField(db_index=True, max_length=8)),
                (
                    "playable_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="gamedata.playableclass",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Playable Specializations",
            },
        ),
        migrations.CreateModel(
            name="ProfessionSkillTier",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier",
                        to="gamedata.profession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profession Skill Tiers",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=96)),
                ("icon", models.CharField(max_length=128)),
                (
                    "crafted_quantity",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedata.profession",
                    ),
                ),
                (
                    "profession_skill_tier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedata.professionskilltier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeReagent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "reagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedata.reagent",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedata.recipe",
                    ),
                ),
            ],
        ),
    ]
