# Generated by Django 5.2.3 on 2025-06-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gamedata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Guild name", max_length=128
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True, help_text="Guild Server/Realm", max_length=128
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Guild icon (not emblem)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("timezone", models.CharField(default="US/Eastern", max_length=64)),
                (
                    "region",
                    models.CharField(
                        choices=[("us", "us"), ("eu", "eu")],
                        help_text="Region to retrieve guild data",
                        max_length=2,
                    ),
                ),
                (
                    "faction",
                    models.CharField(
                        choices=[("Horde", "Horde"), ("Alliance", "Alliance")],
                        help_text="Horde/Alliance",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "short_name",
                    models.CharField(db_index=True, max_length=7, unique=True),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="Color used for display purposes",
                        max_length=7,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guild.guild",
                    ),
                ),
            ],
            options={
                "unique_together": {("guild", "name")},
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Character Name", max_length=32
                    ),
                ),
                ("level", models.IntegerField()),
                ("guild_rank", models.IntegerField(null=True)),
                ("realm", models.CharField(db_index=True, max_length=32)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Wow Avatar Render Image", max_length=128
                    ),
                ),
                ("achievement_points", models.IntegerField(default=0)),
                ("average_item_level", models.IntegerField(default=0)),
                ("equipped_item_level", models.IntegerField(default=0)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "active_spec",
                    models.ForeignKey(
                        help_text="Character's Active Specialization",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="gamedata.playablespecialization",
                    ),
                ),
                ("known_recipes", models.ManyToManyField(to="gamedata.recipe")),
                (
                    "playable_class",
                    models.ForeignKey(
                        help_text="Character's Class",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="gamedata.playableclass",
                    ),
                ),
                (
                    "playable_race",
                    models.ForeignKey(
                        help_text="Character's Race",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="gamedata.playablerace",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guild.guild",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guild.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="WoW character name", max_length=32
                    ),
                ),
                (
                    "discord_name",
                    models.CharField(help_text="Discord name", max_length=32),
                ),
                ("app_data", models.TextField()),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Track state of application.  Has it been delivered to the guild?",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guild.guild"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guild.team",
                    ),
                ),
            ],
        ),
    ]
